config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  #  unauthenticated do
  #   as :user do
  #           root to: "devise/registrations#new"2
  #         end
  #  end

  resources :categories, only: [ :show ]
  resources :products, only: [ :show ]

  get "admin" => "admin#index" # config route with <controller>#page
  get "category" => "category#index"
  get "cart" => "cart#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 70, 70 ]
    attachable.variant :medium, resize_to_limit: [ 250, 250 ]
  end

  has_many :stocks
  has_many :order_products

  def as_json(options = {})
    json = super(options)

    if images.attached?
      json["image_urls"] = images.map do |image|
        url_options = Rails.application.config.action_mailer.default_url_options

        {
          original: Rails.application.routes.url_helpers.rails_blob_url(image, **url_options),
          thumb: Rails.application.routes.url_helpers.rails_representation_url(image.variant(:thumb), **url_options),
          medium: Rails.application.routes.url_helpers.rails_representation_url(image.variant(:medium), **url_options)
        }
      end
    else
      json["image_urls"] = []
    end

    json
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    if params[:query].present?
      @product_pagy, @admin_products = pagy(Product.where("name LIKE ?", "%#{params[:query]}%"))
    else
      @product_pagy, @admin_products = pagy(Product.all)
    end
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_path(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: admin_product_path(@admin_product) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["image"] })
      if admin_product_params["image"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_product_path(@admin_product), notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_product
    @admin_product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def admin_product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :active, images: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product], class: "contents") do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul class="list-disc ml-6">
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": admin_product.errors[:name].none?, "border-red-400 focus:outline-red-600": admin_product.errors[:name].any? }] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": admin_product.errors[:description].none?, "border-red-400 focus:outline-red-600": admin_product.errors[:description].any? }] %>
  </div>

  <div class="my-5">
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, class: "w-50 h-50 objec-cover rounded-md" %>
      <% end %>
    <% end %>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": admin_product.errors[:description].none?, "border-red-400 focus:outline-red-600": admin_product.errors[:description].any? }] %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": admin_product.errors[:price].none?, "border-red-400 focus:outline-red-600": admin_product.errors[:price].any? }] %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": admin_product.errors[:category_id].none?, "border-red-400 focus:outline-red-600": admin_product.errors[:category_id].any? }] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :active %>
    <%= form.check_box :active, class: ["block shadow-sm rounded-md border order-first h-5 w-5", { "border-gray-400 focus:outline-blue-600": admin_product.errors[:active].none?, "border-red-400 focus:outline-red-600": admin_product.errors[:active].any? }] %>
  </div>

<% if admin_product.persisted? %>
  <div class="my-5 flex items-center gap-2">
    <%= link_to "Product Stock", admin_product_stocks_path(admin_product), class: "underline" %>
  </div>
<% end %>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Active:</strong>
    <%= product.active? ? "Yes" : "No" %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<% content_for :title, "Editing product" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Show this product", [:admin, @admin_product], class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<% content_for :title, "Products" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_admin_product_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div class="flex mt-4 mb-8 flex-col md:flex-row items-center justify-center w-full mx-auto max-w-md">
    <%= form_with url: admin_products_path, method: :get, class: "flex flex-col md:flex-row items-center space-y-2 md:space-y-0 md:space-x-2" do |form| %>

      <%= form.text_field :query, placeholder: "Search",
                          class: "rounded-md border border-gray-300 focus:ring-0 focus:ring-blue-300 focus:border-blue-400 text-gray-800 px-3 py-2 w-64 outline-none" %>

      <%= form.submit "Search", class: "cursor-pointer bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded-md w-24" %>

      <%= link_to "Clear", admin_products_path,
                  class: "cursor-pointer bg-red-400 hover:bg-red-500 text-white py-2 px-4 rounded-md w-24 text-center" %>
    <% end %>
  </div>

  <div class="flex flex-col w-full">
  <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full">
      <div class="overflow-x-auto">
        <table class="min-w-full overflow-x-scroll border border-gray-300">
          <thead class="bg-white border-b border-gray-300">
          <tr>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Image
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Name
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Description
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Price
            </th>
          </tr>
          </thead>

          <tbody>
          <% @admin_products.each do |item| %>
            <tr class="bg-gray-50 border-b border-gray-300">
              <td class="px-6 py-4 whitespace-nowrap text-sm text-blue-900 font-medium">
                <%= item.images.any? ? image_tag(item.images.first.variant(:thumb)) : image_tag("https://placehold.co/50x50") %>
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm text-blue-900 font-medium">
                <%= link_to item.name, edit_admin_product_path(item) %>
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                <%= item.description %>
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                $<%= (item.price.to_i / 100.0).to_s %>
              </td>
            </tr>
          <% end %>

          </tbody>
        </table>
        <%== pagy_nav(@product_pagy) if @product_pagy.pages > 1%>
      </div>
    </div>
  </div>
</div>
</div>

app/views/admin/products/new.html.erb
<% content_for :title, "New product" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Back to products", admin_products_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<% content_for :title, "Showing product" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing product</h1>

  <%= render @admin_product %>

  <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>