config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  #  unauthenticated do
  #   as :user do
  #           root to: "devise/registrations#new"2
  #         end
  #  end

  resources :categories, only: [ :show ]
  resources :products, only: [ :show ]

  get "admin" => "admin#index" # config route with <controller>#page
  get "category" => "category#index"
  get "cart" => "cart#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 150, 150 ]
  end

  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_categories, only: %i[ show edit update destroy ]

  # GET /admin/categories or /admin/categories.json
  def index
    @categories = Category.all
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories or /admin/categories.json
  def create
    @category = Category.new(categories_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: admin_category_path(@category) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|
      if @category.update(categories_params)
        format.html { redirect_to admin_category_path(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: admin_category_path(@category) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_categories
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def categories_params
    params.require(:category).permit(:name, :description, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products
    if params[:max].present?
      @products = @products.where("price <= ?", params[:max])
    end
    if params[:min].present?
      @products = @products.where("price >= ?", params[:min])
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/categories/show.html.erb
<h1>Category show page</h1>
<div class="min-h-screen flex justify-center">
  <div class="flex flex-wrap flex-col mt-6">
    <h2 class="text-lg text-gray-800">Filter</h2>
    <%= form_with url: category_path(@category), method: :get, class: "flex flex-col" do |form| %>
      <%= form.number_field :min, placeholder: "Min price", class: "rounded-md border-gray-300 focus:ring-0 focus:ring-blue-300 focus:border-blue-400 text-gray-800 px-3 py-2 outline-none border p-2 w-32" %>
      <%= form.number_field :max, placeholder: "Max price", class: "rounded-md border-gray-300 focus:ring-0 focus:ring-blue-300 focus:border-blue-400 text-gray-800 px-3 py-2 outline-none border p-2 mt-2 w-32" %>
      <%= form.submit "Filter", class: "bg-blue-500 text-white border mt-4 rounded-md p-2 cursor-pointer hover:bg-blue-600 w-32" %>
  <% end %>

    <%= form_with url: category_path(@category), method: :get, class: "flex flex-col" do |form| %>
      <%= form.submit "Clear", class: "cursor-pointer bg-red-400 hover:bg-red-500 text-white py-2 mt-2 px-4 rounded-md w-24 text-center w-32" %>
    <% end %>
  </div>
  <div class="flex flex-wrap mt-6 gap-10 flex-grow justify-center items-start">
    <% if @products.empty? %>
      <p class="text-2xl text-left text-gray-800">No products found</p>
    <% else %>
      <% @products.each do |product| %>
        <%= link_to product_path(product) do %>
          <div class="max-w-xs flex flex-col p-4 justify-center items-center">
            <%= product.images.first ? image_tag(product.images.first.variant(:medium), class: "rounded") : image_tag("https://placehold.co/250", class: "rounded") %>
            <p class="mt-6 font-medium text-gray-800"><%= product.name %></p>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>