config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  #  unauthenticated do
  #   as :user do
  #           root to: "devise/registrations#new"2
  #         end
  #  end

  resources :categories, only: [ :show ]
  resources :products, only: [ :show ]

  get "admin" => "admin#index" # config route with <controller>#page
  get "category" => "category#index"
  get "cart" => "cart#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "E Shop" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<main class="flex">
  <nav class="flex">
    <div class="w-64 p-4 h-screen bg-gray-600 sticky top-0">
      <div class="flex">
        <%= image_tag '/logo.png', class: 'w-10 mr-2' %>
        <h1 class="text-md py-2 text-gray-50 font-bold hidden md:block">E-Shop Admin</h1>
      </div>

      <ul class="flex flex-col text-gray-50">
        <li>
          <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'gauge-high', class: "mr-2") %> <span class="hidden md:inline-block">Dashboard</span>
          <% end %>
        </li>

        <li>
          <%= link_to admin_products_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'cart-shopping', class: "mr-2") %> <span class="hidden md:inline-block">Product</span>
          <% end %>
        </li>

        <li>
          <%= link_to admin_categories_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'list', class: "mr-2") %> <span class="hidden md:inline-block">Categories</span>
          <% end %>
        </li>

        <li>
          <%= link_to admin_orders_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'truck-fast', class: "mr-2") %> <span class="hidden md:inline-block">Orders</span>
          <% end %>
        </li>

        <li>
          <%= link_to destroy_admin_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?" }, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'sign-out', class: "mr-2") %> <span class="hidden md:inline-block">Sign out</span>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <div class="p-8 w-full">
    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "E Shop" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "layouts/shared/navbar" %>
<main class="container mx-auto mt-28 max-w7xl px-2 sm:px-6 lg:px-8">
  <%= yield %>
</main>
<%= render "layouts/shared/footer" %>
</body>
</html>